services:
  api:
    container_name: api
    image: pose-classification-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - pose_classification_network
    volumes:
      - api_db_data:/api/database
      - api_uploads:/api/uploads

  web:
    container_name: web
    image: pose-classification-web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    networks:
      - pose_classification_network
    volumes:
      - web_logs:/web/logs
      - web_public_uploads:/web/public/uploads

networks:
  pose_classification_network:
    driver: bridge

volumes:
  api_db_data:
  api_uploads:
  web_logs:
  web_public_uploads: